### ISSUE TITLE
cmd access is denied

### ISSUE THREAD

**Issue by touchwave-through** [caiohamamura/LenovoBatteryManagementSvc#2]
Cannot successfully run the command, given result is "Access is denied." cmd opened as administrator, security and permission of the folder are allowed to read and execute.

**Comment by caiohamamura** [comment]
That has probably is not caused by this service, but permission issue, because AFAIK the `sc` command, which I assume you are talking about does not validate or try to run the service, but only adds a registry info to the command you provided.
